spring:
  datasource:
    url: jdbc:h2:mem:clone
    username: sa
    password:
    driver-class-name: org.h2.Driver

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL : debug
    org.hibernate.type : trace
#      org.springframework :  debug
#      org.springframework.web : debug

cloud:
  aws:
    credentials:
      access-key: AKIATQWGTCET5WQ7EM63
      secret-key: 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
    region:
      static: ap-northeast-2

    s3:
      bucket: marketkurly-imageupload
    stack:
      auto: false